trigger:
- master

pool:
  name: Self-Hosted-Laptop
  demands: maven



resources:
  repositories:
  - repository: yourGitHubRepo
    type: github
    endpoint: Github-ServiceConnection
    name: sudhvihaan/Azure-CICD-Examples

 
steps:
- script: |
    git clone https://github.com/sudhvihaan/Azure-CICD-Examples.git
    # Now, navigate to the specific subdirectory
    cd Azure-CICD-Examples/03-CICD-PL-Terraform-res-deploy
  displayName: 'Clone and navigate to subdirectory'

  