trigger:
- master

pool:
  name: Self-Hosted-Laptop
  demands: maven



resources:
  repositories:
  - repository: yourGitHubRepo
    type: github
    endpoint: Github-ServiceConnection
    name: sudhvihaan/Azure-CICD-Examples
    ref: master

steps:
  - task:
    name: 
    displayName: hello 
