trigger:
- master

pool:
  name: Self-Hosted-Laptop
  demands: msbuild

resources:
  repositories:
  - repository: AzureCICDGithumb
    type: github
    endpoint: Github-ServiceConnection
    name: sudhvihaan/Azure-CICD-Examples
    ref: 04-CICD-PL-Java-SpringBootApp-AzureApps
    #path: 

stages: 
  - stage: 
    displayName: Build Stage
    jobs:
      - job: 
        steps: 
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false