trigger:
- master

pool:
  name: Self-Hosted-Laptop
  demands: maven



resources:
  repositories:
  - repository: yourGitHubRepo
    type: github
    endpoint: Github-ServiceConnection
    name: sudhvihaan/Azure-CICD-Examples


steps:
- task: Maven@4
  name: asdasd
  