trigger:
- master

pool:
  name: Self-Hosted-Laptop
  demands: maven

resources:
  repositories:
  - repository: yourGitHubRepo
    type: github
    endpoint: git-service-connection
    name: sudhvihaan/Azure-CICD-Examples


stages:
- stage: Stage_CI_Azure_ResourceProvisioning_via_Terraform
  jobs:
    - job: DeployAzureApp
      steps:
      - script: |
          git clone https://github.com/sudhvihaan/Azure-CICD-Examples.git
          # Now, navigate to the specific subdirectory
          cd Azure-CICD-Examples/05-CICDPL-Java-SprintBootApp2-AzureWebApps/Terraform
          displayName: 'DM- Clone Git and navigate to Terraform Directory'