trigger:
- master

pool:
  name: Self-Hosted-Laptop
  demands: maven



resources:
  repositories:
  - repository: yourGitHubRepo
    type: github
    endpoint: Github-ServiceConnection
    name: sudhvihaan/Azure-CICD-Examples

 
steps:
- script: |
    git clone https://github.com/sudhvihaan/Azure-CICD-Examples.git
    # Now, navigate to the specific subdirectory
    cd Azure-CICD-Examples/04-CICD-PL-Java-SpringBootApp-AzureApps
  displayName: 'Clone and navigate to subdirectory'

- task: Maven@3
  inputs:
    mavenPomFile: '04-CICD-PL-Java-SpringBootApp-AzureApps/gs-spring-boot-master/gs-spring-boot-master/app/pom.xml'  # Path to your project's POM file
    goals: 'clean package -Dmaven.test.skip=true'  # Specify the Maven goals, e.g., clean, package, etc.
    publishJUnitResults: true  # If you have JUnit tests, set this to true

- script: |
    ls $(Build.ArtifactStagingDirectory)
  displayName: 'List Artifact Directory'
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path to your built JAR or WAR file
    artifactName: 'MyJavaApp'  # Give your artifact a name

