trigger:
- master

pool:
  name: Self-Hosted-Laptop
  demands: maven

resources:
  repositories:
  - repository: yourGitHubRepo
    type: github
    endpoint: git-service-connection
    name: sudhvihaan/Azure-CICD-Examples


stages:
- stage: Stage_CI_Azure_ResourceProvisioning_via_Terraform
  jobs:
    - job: DeployAzureApp
      displayName: 'DM- Clone Git and navigate to Terraform Directory'
      steps:
      - script: |
          git clone https://github.com/sudhvihaan/Azure-CICD-Examples.git
          # Now, navigate to the specific subdirectory
          cd Azure-CICD-Examples/05-CICDPL-Java-SprintBootApp2-AzureWebApps/Terraform
          


      - task: TerraformTaskV4@4
        displayName: 'DM-Terraform Init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(Build.SourcesDirectory)/05-CICDPL-Java-SprintBootApp2-AzureWebApps/Terraform'
          backendServiceArm: 'service-connection-for-CICD-java-Spring-Boot'
          backendAzureRmResourceGroupName: 'AKS-HEMLDemo'
          backendAzureRmStorageAccountName: 'storageac6674'
          backendAzureRmContainerName: 'storestafefile'
          backendAzureRmKey: 'state-2nd-JSB.tfstate'
