trigger:
- main

stages:
  - stage: InitStage
    jobs:
    - job: Initialize
      continueOnError: false
      steps:
        - task: Checkout@2  # Use the correct task reference format 'Checkout@2'
          inputs:
            repository: 'sudhvihaan/Azure-CICD-Examples'
            ref: 'main'  # Specify the branch you want to check out
            clean: true  # Ensure a clean workspace

        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Azure subscription 1(2)(8bf47336-0c8c-46f5-8b73-3174f08ce9f3)'
            backendAzureRmResourceGroupName: 'RG_DP_ACA'
            backendAzureRmStorageAccountName: 'storestatefile'
            backendAzureRmContainerName: 'dev-statefile'
            backendAzureRmKey: 'test-state'

  - stage: validate
    jobs: 
    - job: validate
      steps:
        - task: Checkout@2  # Use the correct task reference format 'Checkout@2'
          inputs:
            repository: 'sudhvihaan/Azure-CICD-Examples'
            ref: 'main'
            clean: true

        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'validate'
